### ISSUE TITLE
Object Oriented Economics calculation

### ISSUE THREAD

**Issue by cfraces** [dungnguyensarasota/training#1]
Create Economics class:
- Attributes are npv, irr, payout, profitability, dpi (npv/pv of investment)
- Initialize using a dictionary of paramters
- Methods: 
- calculate() to compute value of attributes

User should build and Ecoomic object as:
>> param = {'project_length':20, "mineral_tax":0.025,...}
>> eco = Ecomomics(**param)
>> eco.calculate()
>> print(eco.npv)
... 457740.57...

**Comment by dungnguyensarasota** [comment]
Dear @cfraces Please review the code in feature-oop

**Comment by cfraces** [comment]
Clear
